<a href="https://colab.research.google.com/github/preethamgoud9/-Nanogpt/blob/main/gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt # first the input data

--2025-03-01 06:43:58--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  4.79MB/s    in 0.2s    

2025-03-01 06:43:59 (4.79 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [2]:
with open("input.txt") as f:              #here im opening the file and storing it in var file for later use
  text = f.read()

In [3]:
print(f"length of characters in dataset:,{len(text)}")  #here i printed the overall length of characters in the input text

length of characters in dataset:,1115394


In [4]:
print(text[:1000])  #i'm printing out the first 1000characters in the input text

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [5]:
chars = sorted(list(set(text))) # here i have taken the text and put in function set to get all the chars in the input data and stored in list and sorted then in an order and put in chars for later use
vocab_size = len(chars) # i have stored the length of chars in var named vocab_size
print(''.join(chars))
print(vocab_size)



 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [6]:
stoi = {ch:i for i,ch in enumerate(chars)} # Creates a dictionary (stoi) that maps each character in 'chars' to its index.
itoc = {i:ch for i,ch in enumerate(chars)}  # here we do the same but the exact opposite take int and convert to char
encode = lambda s:[stoi[c] for c in s] # Creates an anonymous function that takes a string 's' and converts each character into its corresponding integer using 'stoi'.
decode = lambda l:[itoc[i] for i in l] # here we do the same but the exact opposite but decodes the int to string



In [7]:
encode("preetham") #here is what the encode function does

[54, 56, 43, 43, 58, 46, 39, 51]

In [8]:
decode([54, 56, 43, 43, 58, 46, 39, 51]) #here is what the decode function does

['p', 'r', 'e', 'e', 't', 'h', 'a', 'm']

In [9]:
import torch
data = torch.tensor(encode(text),dtype =torch.long)  # i have encoded the whole input text into in teger of type long(Which is int64) and converted it into tensor(one dimenional) and stored in var data
print(data.shape ,data.dtype)
print(data[:1000])  #here im outputting the first 1000int output which is encoded from string to int by slicing


torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [10]:
n = int(0.9*len(data))   # here im spliting the data into two sets as train data and validation data into 90 10 percents
train_data = data[:n]    #here im slicing from beginning to n which 90percent of the data cuz of n
val_data = data[n:]      #here im slicing the data from the index n to the end

In [11]:
block_size = 8    # here instead of taking the entire text(dataset) we are dealing in small chucks named block_size
train_data[:block_size+1] #here we are taking the block_size plus 1 set

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [12]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
  context = x[:t+1]
  target = y[t]
  print(f"if the input is {context} the target is : {target}")

if the input is tensor([18]) the target is : 47
if the input is tensor([18, 47]) the target is : 56
if the input is tensor([18, 47, 56]) the target is : 57
if the input is tensor([18, 47, 56, 57]) the target is : 58
if the input is tensor([18, 47, 56, 57, 58]) the target is : 1
if the input is tensor([18, 47, 56, 57, 58,  1]) the target is : 15
if the input is tensor([18, 47, 56, 57, 58,  1, 15]) the target is : 47
if the input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target is : 58


In [13]:
#this is manual implementation of dataset and dataloader in production we can use classes such as dataset and dataloader
#this is manuallly implementing the the mini batch to improve the speed and efficient through parallization of data spliting and training
#can be known as mini batch gradient descent


torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
  data = train_data if split == "train" else val_data
  ix = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  return x,y

xb,yb = get_batch("train")
print("inputs;")
print(xb.shape)
print(xb)
print(yb.shape)
print(yb)
print("-"*25)


for b in range(batch_size):
  for t in range(block_size):
    context = xb[b,:t+1]
    target = yb[b,t]
    print(f"when the input is {context.tolist()} the target is {target}")

inputs;
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
-------------------------
when the input is [24] the target is 43
when the input is [24, 43] the target is 58
when the input is [24, 43, 58] the target is 5
when the input is [24, 43, 58, 5] the target is 57
when the input is [24, 43, 58, 5, 57] the target is 1
when the input is [24, 43, 58, 5, 57, 1] the target is 46
when the input is [24, 43, 58, 5, 57, 1, 46] the target is 43
when the input is [24, 43, 58, 5, 57, 1, 46, 43] the target is 39
when the input is [44] the target is 53
when the input is [44, 53] the target is 56
when the input is [44, 53, 56] the target is 1
when the input is [44, 53, 56, 1] the

In [14]:
print(xb)    #this is our input to the transformer

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [15]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)
['\n', 'S', 'r', '?', 'q', 'P', '-', 'Q', 'W', 'k', 't', 'X', 'o', 'L', '&', 'j', 'L', 'D', 'J', 'g', 'O', 'L', 'V', 'z', "'", 'R', 'I', 'o', 'D', 'q', 'H', 'd', 'h', 's', 'V', '&', 'v', 'L', 'L', 'x', 'a', 't', 'j', 's', 'c', 'M', 'p', 'w', 'L', 'E', 'R', 'S', 'P', 'y', 'a', 'o', '.', 'q', 'f', 'z', 's', '$', 'Y', 's', '$', 'z', 'F', '-', 'w', ',', ';', 'e', 'E', 'k', 'z', 'x', 'j', 'g', 'C', 'K', 'F', 'C', 'h', 's', '!', 'i', 'W', 'W', '.', 'O', 'b', 'z', 'D', 'n', 'x', 'A', ' ', 'M', 's', '$', '3']


In [16]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [17]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.587916374206543


In [18]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

['\n', 'x', 'i', 'K', 'i', '-', 'R', 'J', ':', 'C', 'g', 'q', 'V', 'u', 'U', 'a', '!', 'U', '?', 'q', 'M', 'H', '.', 'u', 'k', '!', 's', 'C', 'u', 'M', 'X', 'v', 'v', '!', 'C', 'J', 'F', 'f', 'x', ';', 'L', 'g', 'R', 'y', 'J', 'k', 'n', 'O', 'E', 't', 'i', '.', '?', 'I', '&', '-', 'g', 'P', 'l', 'L', 'y', 'u', 'l', 'I', 'd', '?', 'X', 'l', 'a', 'I', 'n', 'Q', "'", 'q', ',', 'l', 'T', '$', '\n', '3', 'Q', '&', 's', 'G', 'l', 'v', 'H', 'Q', '?', 'm', 'q', 'S', 'q', '-', 'e', 'O', 'N', '\n', 'x', '?', 'S', 'P', ' ', 'f', 'U', 'A', 'f', 'C', 'A', 'u', 'C', 'X', ':', 'b', 'O', 'l', 'g', 'i', 'R', 'Q', 'W', 'N', ':', 'M', 'p', 'h', 'a', 'w', '\n', 't', 'R', 'L', 'K', 'u', 'Y', 'X', 'E', 'a', 'A', 'X', 'x', 'r', 'c', 'q', '-', 'g', 'C', 'U', 'z', 'e', 'h', '3', 'w', '!', 'A', 'c', 'y', 'a', 'y', 'l', 'g', 'Y', 'W', 'j', 'm', 'J', 'M', '?', 'U', 'z', 'w', ':', 'i', 'n', 'a', 'Y', ',', ':', 'C', '&', 'O', 'E', 'C', 'W', ':', 'v', 'm', 'G', 'G', 'J', 'A', 'n', '3', 'o', 'n', 'A', 'u', 'M', 'g', 

In [19]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [20]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [21]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [22]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False