<a href="https://colab.research.google.com/github/preethamgoud9/-Nanogpt/blob/main/gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt # first the input data

--2025-02-26 14:48:15--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.06s   

2025-02-26 14:48:16 (17.6 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [3]:
with open("input.txt") as f:              #here im opening the file and storing it in var file for later use
  text = f.read()

In [5]:
print(f"length of characters in dataset:,{len(text)}")  #here i printed the overall length of characters in the input text

length of characters in dataset:,1115394


In [6]:
print(text[:1000])  #i'm printing out the first 1000characters in the input text

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [7]:
chars = sorted(list(set(text))) # here i have taken the text and put in function set to get all the chars in the input data and stored in list and sorted then in an order and put in chars for later use
vocab_size = len(chars) # i have stored the length of chars in var named vocab_size
print(''.join(chars))
print(vocab_size)



 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [8]:
stoi = {ch:i for i,ch in enumerate(chars)} # Creates a dictionary (stoi) that maps each character in 'chars' to its index.
itoc = {i:ch for i,ch in enumerate(chars)}  # here we do the same but the exact opposite take int and convert to char
encode = lambda s:[stoi[c] for c in s] # Creates an anonymous function that takes a string 's' and converts each character into its corresponding integer using 'stoi'.
decode = lambda l:[itoc[i] for i in l] # here we do the same but the exact opposite but decodes the int to string



In [9]:
encode("preetham") #here is what the encode function does

[54, 56, 43, 43, 58, 46, 39, 51]

In [10]:
decode([54, 56, 43, 43, 58, 46, 39, 51]) #here is what the decode function does

['p', 'r', 'e', 'e', 't', 'h', 'a', 'm']

In [11]:
import torch
data = torch.tensor(encode(text),dtype =torch.long)  # i have encoded the whole input text into in teger of type long(Which is int64) and converted it into tensor(one dimenional) and stored in var data
print(data.shape ,data.dtype)
print(data[:1000])  #here im outputting the first 1000int output which is encoded from string to int by slicing


torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [12]:
n = int(0.9*len(data))   # here im spliting the data into two sets as train data and validation data into 90 10 percents
train_data = data[:n]    #here im slicing from beginning to n which 90percent of the data cuz of n
val_data = data[n:]      #here im slicing the data from the index n to the end

In [13]:
block_size = 8    # here instead of taking the entire text(dataset) we are dealing in small chucks named block_size
train_data[:block_size+1] #here we are taking the block_size plus 1 set

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [14]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
  context = x[:t+1]
  target = y[t]
  print(f"if the input is {context} the target is : {target}")

if the input is tensor([18]) the target is : 47
if the input is tensor([18, 47]) the target is : 56
if the input is tensor([18, 47, 56]) the target is : 57
if the input is tensor([18, 47, 56, 57]) the target is : 58
if the input is tensor([18, 47, 56, 57, 58]) the target is : 1
if the input is tensor([18, 47, 56, 57, 58,  1]) the target is : 15
if the input is tensor([18, 47, 56, 57, 58,  1, 15]) the target is : 47
if the input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target is : 58


In [43]:
#this is manual implementation of dataset and dataloader in production we can use classes such as dataset and dataloader
#this is manuallly implementing the the mini batch to improve the speed and efficient through parallization of data spliting and training
#can be known as mini batch gradient descent


torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
  data = train_data if split == "train" else val_data
  ix = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  return x,y

xb,yb = get_batch("train")
print("inputs;")
print(xb.shape)
print(xb)
print(yb.shape)
print(yb)
print("-"*25)


for b in range(batch_size):
  for t in range(block_size):
    context = xb[b,:t+1]
    target = yb[b,t]
    print(f"when the input is {context.tolist()} the target is {target}")

inputs;
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
-------------------------
when the input is [24] the target is 43
when the input is [24, 43] the target is 58
when the input is [24, 43, 58] the target is 5
when the input is [24, 43, 58, 5] the target is 57
when the input is [24, 43, 58, 5, 57] the target is 1
when the input is [24, 43, 58, 5, 57, 1] the target is 46
when the input is [24, 43, 58, 5, 57, 1, 46] the target is 43
when the input is [24, 43, 58, 5, 57, 1, 46, 43] the target is 39
when the input is [44] the target is 53
when the input is [44, 53] the target is 56
when the input is [44, 53, 56] the target is 1
when the input is [44, 53, 56, 1] the

In [46]:
print(xb)    #this is our input to the transformer

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [85]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)


class BigramLanguageModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()

    self.token_embedding_table = nn.Embedding(vocab_size,vocab_size)

  def forward(self, idx , targets):

    logits = self.token_embedding_table(idx)
    B , T , C = logits.shape
    logits = logits.view(B*T,C)
    targets = targets.view(B*T)

    loss = F.cross_entropy(logits,targets)
    return logits,loss

m = BigramLanguageModel(vocab_size)
logits,loss = m(xb,yb)
print(logits.shape)
print(loss)



torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)
